# Form implementation generated from reading ui file 'frm_GuardarUsuario.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(641, 568)
        self.frmGuardarUsuario = QtWidgets.QWidget(parent=MainWindow)
        self.frmGuardarUsuario.setObjectName("frmGuardarUsuario")
        self.formLayoutWidget = QtWidgets.QWidget(parent=self.frmGuardarUsuario)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 40, 641, 521))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(parent=self.formLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.btnGuardarUsuario = QtWidgets.QPushButton(parent=self.formLayoutWidget)
        self.btnGuardarUsuario.setObjectName("btnGuardarUsuario")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btnGuardarUsuario)
        self.txtNombre = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtNombre.setObjectName("txtNombre")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtNombre)
        self.txtApellido = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtApellido.setObjectName("txtApellido")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtApellido)
        self.txtUserName = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtUserName.setObjectName("txtUserName")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtUserName)
        self.txtClave = QtWidgets.QLineEdit(parent=self.formLayoutWidget)
        self.txtClave.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.txtClave.setObjectName("txtClave")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.txtClave)
        MainWindow.setCentralWidget(self.frmGuardarUsuario)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Guardar Usuario"))
        self.label.setText(_translate("MainWindow", "Nombre"))
        self.label_2.setText(_translate("MainWindow", "Apellido"))
        self.label_3.setText(_translate("MainWindow", "Nombre Usuario"))
        self.label_4.setText(_translate("MainWindow", "Clave"))
        self.btnGuardarUsuario.setText(_translate("MainWindow", "Guardar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
