# Form implementation generated from reading ui file 'vw_home.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_mw_Seguridad(object):
    def setupUi(self, mw_Seguridad):
        mw_Seguridad.setObjectName("mw_Seguridad")
        mw_Seguridad.resize(1157, 600)
        self.centralwidget = QtWidgets.QWidget(parent=mw_Seguridad)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 1141, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        mw_Seguridad.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=mw_Seguridad)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1157, 22))
        self.menubar.setObjectName("menubar")
        self.menuUsuarios = QtWidgets.QMenu(parent=self.menubar)
        self.menuUsuarios.setObjectName("menuUsuarios")
        self.menuRol = QtWidgets.QMenu(parent=self.menubar)
        self.menuRol.setObjectName("menuRol")
        mw_Seguridad.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=mw_Seguridad)
        self.statusbar.setObjectName("statusbar")
        mw_Seguridad.setStatusBar(self.statusbar)
        self.actionListar_Usuarios = QtGui.QAction(parent=mw_Seguridad)
        self.actionListar_Usuarios.setObjectName("actionListar_Usuarios")
        self.actionAgregar = QtGui.QAction(parent=mw_Seguridad)
        self.actionAgregar.setObjectName("actionAgregar")
        self.actionModificar = QtGui.QAction(parent=mw_Seguridad)
        self.actionModificar.setObjectName("actionModificar")
        self.actionAsignar_Rol = QtGui.QAction(parent=mw_Seguridad)
        self.actionAsignar_Rol.setObjectName("actionAsignar_Rol")
        self.menuUsuarios.addAction(self.actionListar_Usuarios)
        self.menuUsuarios.addAction(self.actionAgregar)
        self.menuUsuarios.addAction(self.actionModificar)
        self.menuUsuarios.addSeparator()
        self.menuUsuarios.addAction(self.actionAsignar_Rol)
        self.menuRol.addSeparator()
        self.menubar.addAction(self.menuUsuarios.menuAction())
        self.menubar.addAction(self.menuRol.menuAction())

        self.retranslateUi(mw_Seguridad)
        QtCore.QMetaObject.connectSlotsByName(mw_Seguridad)

    def retranslateUi(self, mw_Seguridad):
        _translate = QtCore.QCoreApplication.translate
        mw_Seguridad.setWindowTitle(_translate("mw_Seguridad", "Seguridad"))
        self.menuUsuarios.setTitle(_translate("mw_Seguridad", "Usuarios"))
        self.menuRol.setTitle(_translate("mw_Seguridad", "Rol"))
        self.actionListar_Usuarios.setText(_translate("mw_Seguridad", "Listar"))
        self.actionAgregar.setText(_translate("mw_Seguridad", "Agregar"))
        self.actionModificar.setText(_translate("mw_Seguridad", "Modificar"))
        self.actionAsignar_Rol.setText(_translate("mw_Seguridad", "Asignar Rol"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mw_Seguridad = QtWidgets.QMainWindow()
    ui = Ui_mw_Seguridad()
    ui.setupUi(mw_Seguridad)
    mw_Seguridad.show()
    sys.exit(app.exec())
