# Form implementation generated from reading ui file 'vw_lista_usuarios.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_frmListaUsuarios(object):
    def setupUi(self, frmListaUsuarios):
        frmListaUsuarios.setObjectName("frmListaUsuarios")
        frmListaUsuarios.resize(776, 678)
        self.centralwidget = QtWidgets.QWidget(parent=frmListaUsuarios)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(-10, 160, 771, 521))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(6)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_usuarios = QtWidgets.QTableWidget(parent=self.gridLayoutWidget)
        self.tw_usuarios.setObjectName("tw_usuarios")
        self.tw_usuarios.setColumnCount(5)
        self.tw_usuarios.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tw_usuarios.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_usuarios.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_usuarios.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_usuarios.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tw_usuarios.setHorizontalHeaderItem(4, item)
        self.gridLayout.addWidget(self.tw_usuarios, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(320, 60, 121, 21))
        self.label.setObjectName("label")
        frmListaUsuarios.setCentralWidget(self.centralwidget)

        self.retranslateUi(frmListaUsuarios)
        QtCore.QMetaObject.connectSlotsByName(frmListaUsuarios)

    def retranslateUi(self, frmListaUsuarios):
        _translate = QtCore.QCoreApplication.translate
        frmListaUsuarios.setWindowTitle(_translate("frmListaUsuarios", "Lista de Usuarios"))
        item = self.tw_usuarios.horizontalHeaderItem(0)
        item.setText(_translate("frmListaUsuarios", "Id Usuario"))
        item = self.tw_usuarios.horizontalHeaderItem(1)
        item.setText(_translate("frmListaUsuarios", "Nombre"))
        item = self.tw_usuarios.horizontalHeaderItem(2)
        item.setText(_translate("frmListaUsuarios", "Apellido"))
        item = self.tw_usuarios.horizontalHeaderItem(3)
        item.setText(_translate("frmListaUsuarios", "UserName"))
        item = self.tw_usuarios.horizontalHeaderItem(4)
        item.setText(_translate("frmListaUsuarios", "Fecha de Creacion"))
        self.label.setText(_translate("frmListaUsuarios", "Lista de Usuarios"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    frmListaUsuarios = QtWidgets.QMainWindow()
    ui = Ui_frmListaUsuarios()
    ui.setupUi(frmListaUsuarios)
    frmListaUsuarios.show()
    sys.exit(app.exec())
